# Generated by Django 2.2.6 on 2019-10-13 02:46
import json

import requests
from django.db import migrations
from decouple import config


def get_genre():
    get_url = f"https://api.themoviedb.org/3/genre/movie/list?&language=en-US"
    bearer_key = f"Bearer {config('tmdb_apiv4_key')}"
    content_type = "application/json;charset=utf-8"
    header_payload = {"Authorization": bearer_key, "content-type": content_type}
    response = requests.get(get_url, headers=header_payload)
    response_json = json.loads(response.text)
    return response_json


def get_tmdb_genre(apps, schema_editor):

    Genre = apps.get_model('movies_fetch', 'GenreList')
    genre_json = get_genre()
    for i, val in enumerate(genre_json["genres"]):
        genre_entry = Genre(id=i, tmdb_id=int(val["id"]), genre_string=val["name"])
        genre_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies_fetch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_tmdb_genre),
    ]
