before_install: export DJANGO_SETTINGS_MODULE=personal_movie_database.settings
before_script:
- psql -c 'create database "Personal Movie Database";' -U postgres
- psql -c "CREATE USER navbu WITH PASSWORD 'root';" -U postgres
- psql -c "ALTER USER navbu CREATEDB;" -U postgres
- cd personal_movie_database
env:
  global:
  - secure: BKc306GFgIWFAbfeC37U771NB4XbocZtB5In/ygnf3JA+FMXaEtclmWS0dM7MScNaQx3REMI/JncCqMlYYby8xlCfxTKblNWT9591cPp2VlMn5Qm6DW3X6Bde2MCDecYz36mAoRHYj65CR6gsbqC47OWftBl5b+Yl0upzSgJKU71jP3Rrxh2gQSpgw2bAeVX5hC+LDy//R26gWtBts3+4lF2BYMAIiGssoQLm2f2sTutFOH+TPmeg1OJ+ACm6LfrcjU7ZPOu5dMl8Ywzs1OjXhxmDjoJ7/RpJ0A4PZxFu3LPhcGkLdrhyreNRGH9E0R6PwiPWuAMCHpQYjsZ+ztxK+oXxE3JSqvx80TzXp9Yqq4pVoHbLSMCn0ky+lKTpwLfWVSxidzd5jNqDFUJId6CLdQ0BqTKOzsyKB9SgNpkNi52W78Tuslog/RRdKMqA8pGzS9+jWSEcL5BOD/cZnL//RcQKxhJ0pbMxWC3ZismEvBH1WiQfKL6PQTPOireoHewAR1ztLUIvVmDbKUbnI3TfCXC3QB2jCt7drQxtdolDjWMt9spnw/xsSZHrh2F5BR2ASg7+Cbluc9LRxLd/K9Xx9wb8NgbjDiEdy6W7wXe1THrVTfBxRF+CMQ0WqFzrXoTfLtnzYSXUMP4U71HILX0tNZkq1KQhtHi2Ww+qJQ+9fA=
  - secure: dBxCPBSvXxUqbcw3SmyBnbg7ZkhtQKeWfepv6jd5NWG7Skw22Sys3cPh74rj+OV3VRcA8R5siSqjpyl4JQ2XaILlajOtaUxu2qvhFRn9oYyr8cnEF6EMqiJloiubmQAyWWtsuSv4SYvdflTEFNrxM93EVmEO75Q8VxEf2gO7uN1c8vH7qBG9+rAj43F2cy1niNAwUXNfAnXjADr5gVUUXGwne5cWFFygZjlFlJXqTB6O+eucd4umzDogjwHf/Ysslb+cndz/0+vbQujqfoVVDJhVL1QNou151kpa6A4O3rESrxFoWsyJ2H0I9GfI33GxgJS9927a2wGMZeBIbSYI1WwTT96PVtxulprszqJdRuN5jaW0/YG592NjU3YKawR5lbGep20i+sJ4enav2F+Qbj4wVUHkAuVoe6GfEZr5fG7TLvXANNWIF5TLlD/o7nSqPZMO/r1ilCDtwi2plsILj1i1FRQVqHVjN6QUro5W8JfkRqMz9i6YfsCkWQvWXbrcFoTevvg6uVXIQBWXf8R8spXidPz4ZA2z4+MkdMfrRhEnttdSlWP74Es2t5y+FpnN+UIlzsUZVWj9v9MQPKyqrVeAQmchzVTH55AI6gBXZj1VVkctSyPt0iGU0BduVRrpOOOD/gNmLYrSWm4TwweBt4dQ9sBoxsWSb28dXYBYRQk=
  matrix:
  - DJANGO=2.2.6 DJANGO_SETTINGS_MODULE="personal_movie_database.settings"
install:
- pip install -q Django==$DJANGO
- pip install -q -r requirements.txt
language: python
script: python manage.py test
services: postgresql
