before_install: export DJANGO_SETTINGS_MODULE=personal_movie_database.settings
before_script:
- psql -c 'create database "Personal Movie Database";' -U postgres
- psql -c "CREATE USER navbu WITH PASSWORD 'root';" -U postgres
- psql -c "ALTER USER navbu CREATEDB;" -U postgres
- cd personal_movie_database
env:
  global:
  - secure: BKc306GFgIWFAbfeC37U771NB4XbocZtB5In/ygnf3JA+FMXaEtclmWS0dM7MScNaQx3REMI/JncCqMlYYby8xlCfxTKblNWT9591cPp2VlMn5Qm6DW3X6Bde2MCDecYz36mAoRHYj65CR6gsbqC47OWftBl5b+Yl0upzSgJKU71jP3Rrxh2gQSpgw2bAeVX5hC+LDy//R26gWtBts3+4lF2BYMAIiGssoQLm2f2sTutFOH+TPmeg1OJ+ACm6LfrcjU7ZPOu5dMl8Ywzs1OjXhxmDjoJ7/RpJ0A4PZxFu3LPhcGkLdrhyreNRGH9E0R6PwiPWuAMCHpQYjsZ+ztxK+oXxE3JSqvx80TzXp9Yqq4pVoHbLSMCn0ky+lKTpwLfWVSxidzd5jNqDFUJId6CLdQ0BqTKOzsyKB9SgNpkNi52W78Tuslog/RRdKMqA8pGzS9+jWSEcL5BOD/cZnL//RcQKxhJ0pbMxWC3ZismEvBH1WiQfKL6PQTPOireoHewAR1ztLUIvVmDbKUbnI3TfCXC3QB2jCt7drQxtdolDjWMt9spnw/xsSZHrh2F5BR2ASg7+Cbluc9LRxLd/K9Xx9wb8NgbjDiEdy6W7wXe1THrVTfBxRF+CMQ0WqFzrXoTfLtnzYSXUMP4U71HILX0tNZkq1KQhtHi2Ww+qJQ+9fA=
  - secure: Qozo+4uso6dvZLNe+mRUXDllou6LsLJ19XWzGATckO1BW22mUS5j3RicmYpY4XIuo60XwgwR/ywH2Zt01aDkRLqTRskwb0Dt9fJT111/7iHPeYL9JzcFObOWZryXHLKskE32Rcr6GbMal/c//tB5yLMco16OmfDMkcyVzadp9H05a5IS9bQjFEzDlz8yMEBrBoc+u5aeDHZFnj5yjgl7w0DFcTndAzpG90OLCbfAL61eAPnVUAn6G8U1+GGpbiVJPGnZSUzdo1X6353UwO6VwXT7dK1PTjB7P/b/vzpB8E9vhPFvt7o1NKGAbwC3qYHy8GUPCN/V8jqTeVhV/AyPNtuokpcYf0o2F+xu8DjjbYxxdLw5sJLWEsongW6oKuXD6FYHy4k+kL9FoO91cYubfcg6ycIBY3jV1pX7aflfNFXibgFoovPGmhEupTGwjRVsVOUgkRcNRPCmmn4OJ8AX1qI3VfHl1j7M0k52hD7HJR1HGnu0I+d68PxCtIYkREGVbtvSro8qS7mQGGnyHVUguSW5UJccUHlYHC+N1ZIHtzyjK0fadgXg8o0UnRK3A0F30ucz08Bh73meRqpCGc5ugxKVuDQFNb1CdsKrIt7FwGYw3qlLnth+DlJJ4YL1ViTMlrCBmG35+WnhXdnMEL6DItqdlpX95hlLYWWq0nB4BaQ=
  matrix:
  - DJANGO=2.2.6 DJANGO_SETTINGS_MODULE="personal_movie_database.settings"
install:
- pip install -q Django==$DJANGO
- pip install -q -r requirements.txt
language: python
script: python manage.py test
services: postgresql
